apiVersion: v1
kind: Service
metadata:
  name: load-blancer
spec:
  ports:
  # Порт сетевого балансировщика, на котором будут обслуживаться пользовательские запросы.
  - port: 80
    name: k8s-cbcf5ef17c3c92394d6bcf4d602a77a10c7de796
    # Порт контейнера, на котором доступно приложение.
    targetPort: 8080
  # Метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    app: gateway
  type: LoadBalancer
