rating:
  service:
    port: 8050
    image:
      name: sereginamaria/rating
      version: "latest"
    database:
      name: rating
library:
  service:
    port: 8060
    image:
      name: sereginamaria/library
      version: "latest"
    database:
      name: library
reservation:
  service:
    port: 8070
    image:
      name: sereginamaria/reservation
      version: "latest"
    database:
      name: reservation
gateway:
  service:
    port: 8080
    image:
      name: sereginamaria/gateway
      version: "latest"
    isGateway: true
