name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
  KUBE_URL: ${{ secrets.KUBE_URL }}
  KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s
      - name: Build, publish to docker hub
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker build --no-cache -t sereginamaria/gateway ./src/gateway/ && docker push sereginamaria/gateway:latest
          docker build --no-cache -t sereginamaria/rating ./src/rating/ && docker push sereginamaria/rating:latest
          docker build --no-cache -t sereginamaria/library ./src/library/ && docker push sereginamaria/library:latest
          docker build --no-cache -t sereginamaria/reservation ./src/reservation/ && docker push sereginamaria/reservation:latest

      - name: Deploy to k8s
        run: |
          kubectl config set-cluster rsoi --server="$KUBE_URL" --insecure-skip-tls-verify=true
          kubectl config set-credentials admin-user --token="$KUBE_TOKEN"
          kubectl config set-context default --cluster=rsoi --user=admin-user
          kubectl config use-context default
          cd k8s
          helm delete postgres --namespace default || true
          sleep 30
          helm install postgres postgres-chart
          helm delete services --namespace default || true
          sleep 30
          helm install services services-chart
          sleep 65

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
          uses: Romanow/google-sheet-autograder-marker@v1.0
          with:
            google_token: ${{secrets.GOOGLE_API_KEY}}
            sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
            homework_number: 5
            user_column: 'D'
            column_offset: 'F'
            mark: "'+"

